library(citrus)
citrus.launchUI()

set.seed(42)
startTime <- Sys.time()
    # as generated by citrus.launchUI(), but with removal from 
    # the rm(list = ls()) line so we can measure time 
    source("citrus/citrusOutput/runCitrus.R")
t_citrus <- Sys.time() - startTime
